name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * MON'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
          sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
          curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
          sudo dpkg -i cuda-keyring_1.0-1_all.deb
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
          sudo apt-get update -q
          sudo apt-get install cuda -y --no-install-recommends

      - name: Checkout the Repository
        uses: actions/checkout@v2
      
      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          target: nvptx64-nvidia-cuda
          override: true

      - name: Install the rust-ptx-linker
        run: |
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
          sudo ./llvm.sh $(rustc --version -v | grep -oP "LLVM version: \K\d+")
          rm llvm.sh
          cargo install rust-ptx-linker --git https://github.com/juntyr/rust-ptx-linker --force
      
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Check feature powerset on the CPU
        run: |
          cargo hack check --feature-powerset --optional-deps \
            --skip device \
            --keep-going

      - name: Check feature powerset on CUDA
        run: |
          cargo hack check --feature-powerset --optional-deps \
            --skip host,rustacuda,rustacuda_derive,regex \
            --keep-going \
            --target nvptx64-nvidia-cuda

      - name: Check all workspace targets
        run: |
          cargo check --workspace --all-targets

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
          sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
          curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
          sudo dpkg -i cuda-keyring_1.0-1_all.deb
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
          sudo apt-get update -q
          sudo apt-get install cuda -y --no-install-recommends

      - name: Checkout the Repository
        uses: actions/checkout@v2
      
      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          target: nvptx64-nvidia-cuda
          override: true

      - name: Install the rust-ptx-linker
        run: |
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
          sudo ./llvm.sh $(rustc --version -v | grep -oP "LLVM version: \K\d+")
          rm llvm.sh
          cargo install rust-ptx-linker --git https://github.com/juntyr/rust-ptx-linker --force
      
      - name: Run the test-suite
        run: |
          cargo test --workspace --no-fail-fast

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: true

      - name: Check the code formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
          sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
          curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
          sudo dpkg -i cuda-keyring_1.0-1_all.deb
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
          sudo apt-get update -q
          sudo apt-get install cuda -y --no-install-recommends

      - name: Checkout the Repository
        uses: actions/checkout@v2
      
      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy
          target: nvptx64-nvidia-cuda
          override: true

      - name: Install the rust-ptx-linker
        run: |
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
          sudo ./llvm.sh $(rustc --version -v | grep -oP "LLVM version: \K\d+")
          rm llvm.sh
          cargo install rust-ptx-linker --git https://github.com/juntyr/rust-ptx-linker --force

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      
      - name: Check feature powerset on the CPU
        run: |
          cargo hack clippy --feature-powerset --optional-deps \
            --skip device \
            --keep-going \
            -- -D warnings
      
      - name: Check feature powerset on CUDA
        run: |
          cargo hack clippy --feature-powerset --optional-deps \
            --skip host,rustacuda,rustacuda_derive,regex \
            --keep-going \
            --target nvptx64-nvidia-cuda \
            -- -D warnings

      - name: Check all workspace targets
        run: |
          cargo clippy --workspace --all-targets -- -D warnings
