name: Rebase Pull Requests

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Pull Requests
        uses: peter-evans/rebase@v2
        with:
          base: main
