name: rustdoc to gh-pages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.18
        with:
          method: network
          use-github-cache: false
          use-local-cache: false

      - name: Checkout the Repository
        uses: actions/checkout@v2
      
      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: false # FIXME

      - name: Build the Documentation
        run: |
          RUSTDOCFLAGS="\
            --enable-index-page \
            --extern-html-root-url const_type_layout=https://docs.rs/const-type-layout/0.3.2/ \
            --extern-html-root-url final=https://docs.rs/final/0.1.1/ \
            --extern-html-root-url cust=https://docs.rs/cust/0.3.2/ \
            --extern-html-root-url cust_core=https://docs.rs/cust_core/0.1/ \
            --extern-html-root-url cust_derive=https://docs.rs/cust_derive/0.2/ \
            -Zunstable-options \
          " cargo doc \
            --all-features \
            --no-deps

      - name: Deploy the Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
